[package]
name = "integration_test"
version = "0.1.0"
edition = "2021"
workspace = ".."

[dependencies]
holder = { path = "../holder" }
verifier = { path = "../verifier" }

anyhow = { version = "1.0" }
env_logger = { version = "0.11" }
log = { version = "0.4" }