[package]
name = "holder"
version = "0.1.0"
edition = "2021"
workspace = ".."

[dependencies]
shared = { path = "../shared" }

ring = { version = "0.17" }
thiserror = { version = "1.0" }
log = { version = "0.4" }